"""create lean trading core schema

Revision ID: 20260718_0001
Revises:
Create Date: 2026-07-18 23:49:29.059897
"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260718_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_equities",
        sa.Column("account_equity_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.String(length=120), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("equity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("available_balance", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("withdrawable_balance", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("currency", sa.String(length=32), nullable=False),
        sa.Column("location_type", sa.String(length=16), server_default="VENUE", nullable=False),
        sa.Column(
            "control_status", sa.String(length=16), server_default="READ_ONLY", nullable=False
        ),
        sa.Column("deposit_status", sa.String(length=16), server_default="READY", nullable=False),
        sa.Column("network", sa.String(length=64), nullable=True),
        sa.Column("address_reference", sa.String(length=255), nullable=True),
        sa.Column("fact_status", sa.String(length=16), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("fact_status IN ('KNOWN','UNKNOWN')", name="ck_account_equities_status"),
        sa.CheckConstraint(
            "available_balance >= 0", name="ck_account_equities_balance_nonnegative"
        ),
        sa.CheckConstraint(
            "withdrawable_balance IS NULL OR withdrawable_balance >= 0",
            name="ck_account_equities_withdrawable_nonnegative",
        ),
        sa.CheckConstraint(
            "location_type IN ('VENUE','VAULT')", name="ck_account_equities_location_type"
        ),
        sa.CheckConstraint(
            "control_status IN ('CONTROLLED','READ_ONLY','UNKNOWN')",
            name="ck_account_equities_control_status",
        ),
        sa.CheckConstraint(
            "deposit_status IN ('READY','PENDING','UNKNOWN')",
            name="ck_account_equities_deposit_status",
        ),
        sa.CheckConstraint("equity >= 0", name="ck_account_equities_equity_nonnegative"),
        sa.CheckConstraint(
            "environment IN ('SHADOW','TESTNET','LIVE')",
            name="ck_account_equities_environment",
        ),
        sa.PrimaryKeyConstraint("account_equity_id"),
        sa.UniqueConstraint("environment", "account_id", "venue", name="uq_account_equities_scope"),
    )
    op.create_table(
        "audit_events",
        sa.Column("audit_event_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("object_type", sa.String(length=120), nullable=False),
        sa.Column("object_id", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("object_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("audit_event_id"),
    )
    op.create_index(
        "ix_audit_events_correlation",
        "audit_events",
        ["correlation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_object",
        "audit_events",
        ["object_type", "object_id", "created_at"],
        unique=False,
    )
    capability_gates = op.create_table(
        "capability_gates",
        sa.Column("capability_key", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("operator_id", sa.String(length=255), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "capability_key IN ('LIVE_ORDER_SEND','CAPITAL_TRANSFER','AUTO_ADD')",
            name="ck_capability_gates_key",
        ),
        sa.CheckConstraint("status IN ('DISABLED','ENABLED')", name="ck_capability_gates_status"),
        sa.PrimaryKeyConstraint("capability_key"),
    )
    seeded_at = datetime.now(UTC)
    op.bulk_insert(
        capability_gates,
        [
            {
                "capability_key": "LIVE_ORDER_SEND",
                "status": "DISABLED",
                "reason": "No real venue sender is implemented",
                "operator_id": "migration",
                "updated_at": seeded_at,
            },
            {
                "capability_key": "CAPITAL_TRANSFER",
                "status": "DISABLED",
                "reason": "No real capital transfer is implemented",
                "operator_id": "migration",
                "updated_at": seeded_at,
            },
            {
                "capability_key": "AUTO_ADD",
                "status": "DISABLED",
                "reason": "Automatic Add is default-off",
                "operator_id": "migration",
                "updated_at": seeded_at,
            },
        ],
    )
    op.create_table(
        "command_receipts",
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("caller_id", sa.String(length=255), nullable=False),
        sa.Column("operation", sa.String(length=120), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("semantic_hash", sa.String(length=64), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(semantic_hash) = 64", name="ck_command_receipts_hash"),
        sa.PrimaryKeyConstraint("receipt_id"),
        sa.UniqueConstraint(
            "caller_id", "operation", "idempotency_key", name="uq_command_receipts_scope"
        ),
    )
    op.create_table(
        "instruments",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=120), nullable=False),
        sa.Column("tick_size", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("lot_size", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("minimum_notional", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("contract_multiplier", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("quote_currency", sa.String(length=32), nullable=False),
        sa.Column("collateral_currency", sa.String(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("protection_supported", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("contract_multiplier > 0", name="ck_instruments_multiplier_positive"),
        sa.CheckConstraint("lot_size > 0", name="ck_instruments_lot_size_positive"),
        sa.CheckConstraint("minimum_notional >= 0", name="ck_instruments_min_notional_nonnegative"),
        sa.CheckConstraint("tick_size > 0", name="ck_instruments_tick_size_positive"),
        sa.PrimaryKeyConstraint("instrument_id"),
        sa.UniqueConstraint("venue", "symbol", name="uq_instruments_venue_symbol"),
    )
    op.create_table(
        "risk_policies",
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("system_state", sa.String(length=32), nullable=False),
        sa.Column("max_total_risk", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("max_fact_age_seconds", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.String(length=255), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "system_state IN ('NORMAL','NO_PYRAMID','REDUCE_ONLY','KILL_SWITCH')",
            name="ck_risk_policies_system_state",
        ),
        sa.CheckConstraint("max_fact_age_seconds > 0", name="ck_risk_policies_age_positive"),
        sa.CheckConstraint("max_total_risk > 0", name="ck_risk_policies_max_risk_positive"),
        sa.PrimaryKeyConstraint("policy_id"),
        sa.UniqueConstraint("version"),
    )
    op.create_index(
        "uq_risk_policies_one_active",
        "risk_policies",
        ["active"],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    op.create_table(
        "sender_leases",
        sa.Column("execution_scope", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("fencing_token", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("fencing_token >= 1", name="ck_sender_leases_token_positive"),
        sa.PrimaryKeyConstraint("execution_scope"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("identity_subject", sa.String(length=255), nullable=True),
        sa.Column("telegram_chat_id", sa.String(length=120), nullable=True),
        sa.Column("principal_type", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("principal_type IN ('HUMAN','SERVICE')", name="ck_users_principal_type"),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("identity_subject"),
        sa.UniqueConstraint("telegram_chat_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "positions",
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.String(length=120), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("average_entry_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("mark_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("fact_status", sa.String(length=16), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("fact_status IN ('KNOWN','UNKNOWN')", name="ck_positions_fact_status"),
        sa.CheckConstraint(
            "environment IN ('SHADOW','TESTNET','LIVE')", name="ck_positions_environment"
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.instrument_id"],
        ),
        sa.PrimaryKeyConstraint("position_id"),
        sa.UniqueConstraint(
            "environment",
            "account_id",
            "venue",
            "instrument_id",
            name="uq_positions_scope",
        ),
    )
    op.create_table(
        "proposals",
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("proposer_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_id", sa.String(length=120), nullable=True),
        sa.Column("strategy_version", sa.String(length=120), nullable=True),
        sa.Column("source_candidate_id", sa.String(length=160), nullable=True),
        sa.Column("source_link", sa.Text(), nullable=True),
        sa.Column("source_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_readiness", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("risk_tier", sa.String(length=16), nullable=False),
        sa.Column("account_id", sa.String(length=120), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("max_risk", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("frozen_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("semantic_hash", sa.String(length=64), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("direction IN ('LONG','SHORT')", name="ck_proposals_direction"),
        sa.CheckConstraint(
            "environment IN ('SHADOW','TESTNET','LIVE')", name="ck_proposals_environment"
        ),
        sa.CheckConstraint("risk_tier IN ('LOW','MEDIUM','HIGH')", name="ck_proposals_risk_tier"),
        sa.CheckConstraint("source IN ('SYSTEM','MANUAL')", name="ck_proposals_source"),
        sa.CheckConstraint(
            "source = 'MANUAL' OR (strategy_id IS NOT NULL AND strategy_version IS NOT NULL)",
            name="ck_proposals_system_strategy",
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','PENDING_REVIEW','APPROVED','REJECTED','EXPIRED')",
            name="ck_proposals_status",
        ),
        sa.CheckConstraint("max_risk > 0", name="ck_proposals_risk_positive"),
        sa.CheckConstraint("quantity > 0", name="ck_proposals_quantity_positive"),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.instrument_id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposer_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("proposal_id"),
    )
    op.create_index(
        "ix_proposals_status_expires", "proposals", ["status", "expires_at"], unique=False
    )
    op.create_index(
        "uq_proposals_system_candidate",
        "proposals",
        ["source_candidate_id"],
        unique=True,
        postgresql_where=sa.text("source = 'SYSTEM' AND source_candidate_id IS NOT NULL"),
    )
    op.create_table(
        "transfer_proposals",
        sa.Column("transfer_proposal_id", sa.Uuid(), nullable=False),
        sa.Column("proposer_id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("direction", sa.String(length=24), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.String(length=120), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.String(length=160), nullable=False),
        sa.Column("destination_type", sa.String(length=16), nullable=False),
        sa.Column("destination_id", sa.String(length=160), nullable=False),
        sa.Column("asset", sa.String(length=32), nullable=False),
        sa.Column("network", sa.String(length=64), nullable=False),
        sa.Column("destination_reference", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("max_fee", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("min_received", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("frozen_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("semantic_hash", sa.String(length=64), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "environment IN ('SHADOW','TESTNET','LIVE')",
            name="ck_transfer_proposals_environment",
        ),
        sa.CheckConstraint(
            "direction IN ('VAULT_TO_VENUE','VENUE_TO_VAULT')",
            name="ck_transfer_proposals_direction",
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','PENDING_REVIEW','APPROVED','REJECTED','EXPIRED')",
            name="ck_transfer_proposals_status",
        ),
        sa.CheckConstraint(
            "((direction = 'VAULT_TO_VENUE' "
            "AND source_type = 'VAULT' AND destination_type = 'VENUE') "
            "OR (direction = 'VENUE_TO_VAULT' "
            "AND source_type = 'VENUE' AND destination_type = 'VAULT'))",
            name="ck_transfer_proposals_endpoint_direction",
        ),
        sa.CheckConstraint("amount > 0", name="ck_transfer_proposals_amount_positive"),
        sa.CheckConstraint("max_fee >= 0", name="ck_transfer_proposals_fee_nonnegative"),
        sa.CheckConstraint(
            "min_received > 0 AND min_received <= amount",
            name="ck_transfer_proposals_min_received",
        ),
        sa.ForeignKeyConstraint(["proposer_id"], ["users.user_id"]),
        sa.PrimaryKeyConstraint("transfer_proposal_id"),
    )
    op.create_index(
        "ix_transfer_proposals_status_expires",
        "transfer_proposals",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_table(
        "role_assignments",
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("account_scope", sa.String(length=120), nullable=True),
        sa.Column("venue_scope", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IN ('OBSERVER','PROPOSER','REVIEWER','OPERATOR','TREASURY_ADMIN','SYSTEM_ADMIN')",
            name="ck_role_assignments_role",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("assignment_id"),
    )
    op.create_index("ix_role_assignments_user", "role_assignments", ["user_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("approval_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=True),
        sa.Column("transfer_proposal_id", sa.Uuid(), nullable=True),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(proposal_id IS NOT NULL) <> (transfer_proposal_id IS NOT NULL)",
            name="ck_approvals_one_parent",
        ),
        sa.CheckConstraint("decision IN ('APPROVE','REJECT')", name="ck_approvals_decision"),
        sa.ForeignKeyConstraint(["proposal_id"], ["proposals.proposal_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["transfer_proposal_id"],
            ["transfer_proposals.transfer_proposal_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("approval_id"),
    )
    op.create_index(
        "uq_approvals_proposal_reviewer",
        "approvals",
        ["proposal_id", "reviewer_id"],
        unique=True,
        postgresql_where=sa.text("proposal_id IS NOT NULL"),
    )
    op.create_index(
        "uq_approvals_transfer_reviewer",
        "approvals",
        ["transfer_proposal_id", "reviewer_id"],
        unique=True,
        postgresql_where=sa.text("transfer_proposal_id IS NOT NULL"),
    )
    op.create_table(
        "transfer_authorizations",
        sa.Column("transfer_authorization_id", sa.Uuid(), nullable=False),
        sa.Column("transfer_proposal_id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("direction", sa.String(length=24), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=120), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.String(length=160), nullable=False),
        sa.Column("destination_type", sa.String(length=16), nullable=False),
        sa.Column("destination_id", sa.String(length=160), nullable=False),
        sa.Column("asset", sa.String(length=32), nullable=False),
        sa.Column("network", sa.String(length=64), nullable=False),
        sa.Column("destination_reference", sa.String(length=255), nullable=False),
        sa.Column("amount_limit", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("max_fee", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("min_received", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "environment IN ('SHADOW','TESTNET','LIVE')",
            name="ck_transfer_authorizations_environment",
        ),
        sa.CheckConstraint(
            "direction IN ('VAULT_TO_VENUE','VENUE_TO_VAULT')",
            name="ck_transfer_authorizations_direction",
        ),
        sa.CheckConstraint("amount_limit > 0", name="ck_transfer_authorizations_amount_positive"),
        sa.CheckConstraint("max_fee >= 0", name="ck_transfer_authorizations_fee_nonnegative"),
        sa.CheckConstraint(
            "min_received > 0 AND min_received <= amount_limit",
            name="ck_transfer_authorizations_min_received",
        ),
        sa.ForeignKeyConstraint(
            ["transfer_proposal_id"], ["transfer_proposals.transfer_proposal_id"]
        ),
        sa.PrimaryKeyConstraint("transfer_authorization_id"),
        sa.UniqueConstraint("transfer_proposal_id", name="uq_transfer_authorizations_proposal"),
    )
    op.create_table(
        "capital_transfers",
        sa.Column("capital_transfer_id", sa.Uuid(), nullable=False),
        sa.Column("transfer_authorization_id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("account_id", sa.String(length=120), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("direction", sa.String(length=24), nullable=False),
        sa.Column("source_id", sa.String(length=160), nullable=False),
        sa.Column("destination_id", sa.String(length=160), nullable=False),
        sa.Column("asset", sa.String(length=32), nullable=False),
        sa.Column("network", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("reserved_amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("source_balance_before", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("destination_balance_before", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("fee_amount", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("net_received", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("external_transfer_id", sa.String(length=255), nullable=True),
        sa.Column("transaction_reference", sa.String(length=255), nullable=True),
        sa.Column("reconciliation_status", sa.String(length=32), nullable=False),
        sa.Column(
            "reconciliation_details", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('SOURCE_RESERVED','SUBMITTED','IN_FLIGHT','DESTINATION_CONFIRMED',"
            "'SETTLED','UNKNOWN','FAILED_SOURCE_RESTORED','MANUAL_REQUIRED')",
            name="ck_capital_transfers_status",
        ),
        sa.CheckConstraint("gross_amount > 0", name="ck_capital_transfers_gross_positive"),
        sa.CheckConstraint(
            "reserved_amount = gross_amount", name="ck_capital_transfers_reserved_exact"
        ),
        sa.CheckConstraint(
            "fee_amount IS NULL OR fee_amount >= 0",
            name="ck_capital_transfers_fee_nonnegative",
        ),
        sa.CheckConstraint(
            "net_received IS NULL OR net_received > 0",
            name="ck_capital_transfers_net_positive",
        ),
        sa.ForeignKeyConstraint(
            ["transfer_authorization_id"],
            ["transfer_authorizations.transfer_authorization_id"],
        ),
        sa.PrimaryKeyConstraint("capital_transfer_id"),
        sa.UniqueConstraint("transfer_authorization_id", name="uq_capital_transfers_authorization"),
    )
    op.create_index(
        "ix_capital_transfers_status_updated",
        "capital_transfers",
        ["status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "protection_orders",
        sa.Column("protection_id", sa.Uuid(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("venue_order_id", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("trigger_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("fully_covered", sa.Boolean(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('ACTIVE','DEGRADED','UNKNOWN')", name="ck_protection_status"
        ),
        sa.CheckConstraint("quantity >= 0", name="ck_protection_quantity_nonnegative"),
        sa.CheckConstraint("trigger_price >= 0", name="ck_protection_trigger_nonnegative"),
        sa.ForeignKeyConstraint(["position_id"], ["positions.position_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("protection_id"),
        sa.UniqueConstraint("position_id", name="uq_protection_orders_position"),
    )
    op.create_table(
        "risk_decisions",
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("input_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("approved_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("risk_amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("result IN ('ALLOW','SCALE','DENY')", name="ck_risk_decisions_result"),
        sa.CheckConstraint("approved_quantity >= 0", name="ck_risk_decisions_quantity_nonnegative"),
        sa.CheckConstraint("risk_amount >= 0", name="ck_risk_decisions_risk_nonnegative"),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["risk_policies.policy_id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.proposal_id"],
        ),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_index(
        "ix_risk_decisions_proposal_created",
        "risk_decisions",
        ["proposal_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "trading_authorizations",
        sa.Column("authorization_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("risk_decision_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.String(length=120), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("quantity_limit", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("used_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("risk_limit", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("allowed_adds", sa.Integer(), nullable=False),
        sa.Column("used_adds", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("direction IN ('LONG','SHORT')", name="ck_authorizations_direction"),
        sa.CheckConstraint(
            "environment IN ('SHADOW','TESTNET','LIVE')",
            name="ck_authorizations_environment",
        ),
        sa.CheckConstraint("allowed_adds >= 0", name="ck_authorizations_adds_nonnegative"),
        sa.CheckConstraint("quantity_limit > 0", name="ck_authorizations_quantity_positive"),
        sa.CheckConstraint("risk_limit > 0", name="ck_authorizations_risk_positive"),
        sa.CheckConstraint(
            "used_adds >= 0 AND used_adds <= allowed_adds", name="ck_authorizations_adds"
        ),
        sa.CheckConstraint(
            "used_quantity <= quantity_limit", name="ck_authorizations_used_within_limit"
        ),
        sa.CheckConstraint("used_quantity >= 0", name="ck_authorizations_used_nonnegative"),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.instrument_id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.proposal_id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_decision_id"],
            ["risk_decisions.decision_id"],
        ),
        sa.PrimaryKeyConstraint("authorization_id"),
        sa.UniqueConstraint("proposal_id", name="uq_trading_authorizations_proposal"),
    )
    op.create_table(
        "campaigns",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("authorization_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.String(length=120), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("current_target_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("target_version", sa.Integer(), nullable=False),
        sa.Column("target_reason", sa.Text(), nullable=True),
        sa.Column("target_urgency", sa.String(length=24), nullable=True),
        sa.Column("target_calculated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("final_pnl", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("direction IN ('LONG','SHORT')", name="ck_campaigns_direction"),
        sa.CheckConstraint(
            "environment IN ('SHADOW','TESTNET','LIVE')", name="ck_campaigns_environment"
        ),
        sa.CheckConstraint(
            "status IN ('OPENING','OPEN','REDUCING','CLOSING','CLOSED','UNKNOWN')",
            name="ck_campaigns_status",
        ),
        sa.CheckConstraint("current_target_quantity >= 0", name="ck_campaigns_target_nonnegative"),
        sa.CheckConstraint("target_version >= 0", name="ck_campaigns_target_version_nonnegative"),
        sa.ForeignKeyConstraint(
            ["authorization_id"],
            ["trading_authorizations.authorization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.instrument_id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.proposal_id"],
        ),
        sa.PrimaryKeyConstraint("campaign_id"),
        sa.UniqueConstraint("authorization_id", name="uq_campaigns_authorization"),
    )
    op.create_index(
        "uq_campaigns_one_unclosed_scope",
        "campaigns",
        ["account_id", "venue", "environment", "instrument_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'CLOSED'"),
    )
    op.create_table(
        "funding_payments",
        sa.Column("funding_payment_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("account_id", sa.String(length=120), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("venue_payment_id", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("currency", sa.String(length=32), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "environment IN ('SHADOW','TESTNET','LIVE')",
            name="ck_funding_payments_environment",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.campaign_id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.instrument_id"],
        ),
        sa.PrimaryKeyConstraint("funding_payment_id"),
        sa.UniqueConstraint(
            "environment",
            "account_id",
            "venue",
            "venue_payment_id",
            name="uq_funding_payments_external",
        ),
    )
    op.create_index(
        "ix_funding_payments_campaign_time",
        "funding_payments",
        ["campaign_id", "paid_at"],
        unique=False,
    )
    op.create_index(
        "ix_funding_payments_scope",
        "funding_payments",
        ["environment", "account_id", "venue", "instrument_id"],
        unique=False,
    )
    op.create_table(
        "reconciliation_runs",
        sa.Column("reconciliation_id", sa.Uuid(), nullable=False),
        sa.Column("execution_scope", sa.String(length=255), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("is_computed", sa.Boolean(), nullable=False),
        sa.Column("differences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolution_reason", sa.Text(), nullable=True),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('MATCH','DIFFERENCE','UNKNOWN','MANUAL_REQUIRED','RESOLVED')",
            name="ck_reconciliation_runs_status",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.campaign_id"],
        ),
        sa.PrimaryKeyConstraint("reconciliation_id"),
    )
    op.create_index(
        "ix_reconciliation_scope_completed",
        "reconciliation_runs",
        ["execution_scope", "completed_at"],
        unique=False,
    )
    op.create_table(
        "risk_reservations",
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("authorization_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('RESERVED','OPEN','UNKNOWN','RELEASED')", name="ck_risk_reservations_status"
        ),
        sa.CheckConstraint("amount >= 0", name="ck_risk_reservations_amount_nonnegative"),
        sa.ForeignKeyConstraint(
            ["authorization_id"],
            ["trading_authorizations.authorization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.campaign_id"],
        ),
        sa.PrimaryKeyConstraint("reservation_id"),
    )
    op.create_index(
        "ix_risk_reservations_campaign_status",
        "risk_reservations",
        ["campaign_id", "status"],
        unique=False,
    )
    op.create_table(
        "order_intents",
        sa.Column("intent_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("authorization_id", sa.Uuid(), nullable=False),
        sa.Column("reservation_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("reduce_only", sa.Boolean(), nullable=False),
        sa.Column("trigger_source", sa.String(length=255), nullable=True),
        sa.Column("trigger_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("add_unit_consumed", sa.Boolean(), nullable=False),
        sa.Column("target_version", sa.Integer(), nullable=True),
        sa.Column("position_id", sa.Uuid(), nullable=True),
        sa.Column("position_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("semantic_hash", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('INITIAL','ADD','REDUCE','EXIT')", name="ck_order_intents_kind"
        ),
        sa.CheckConstraint("side IN ('BUY','SELL')", name="ck_order_intents_side"),
        sa.CheckConstraint(
            "status IN ('PENDING','RESERVED','READY','SENT','PARTIALLY_FILLED','FILLED',"
            "'CANCELLED','REJECTED','UNKNOWN')",
            name="ck_order_intents_status",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_order_intents_quantity_positive"),
        sa.CheckConstraint(
            "limit_price IS NULL OR limit_price > 0",
            name="ck_order_intents_limit_price_positive",
        ),
        sa.CheckConstraint(
            "kind = 'ADD' OR add_unit_consumed = false",
            name="ck_order_intents_add_unit_kind",
        ),
        sa.ForeignKeyConstraint(
            ["authorization_id"],
            ["trading_authorizations.authorization_id"],
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.campaign_id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.position_id"],
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["risk_reservations.reservation_id"],
        ),
        sa.PrimaryKeyConstraint("intent_id"),
        sa.UniqueConstraint("reservation_id", name="uq_order_intents_reservation"),
    )
    op.create_index(
        "ix_order_intents_campaign_status", "order_intents", ["campaign_id", "status"], unique=False
    )
    op.create_index(
        "uq_order_intents_one_active_campaign",
        "order_intents",
        ["campaign_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('PENDING','RESERVED','READY','SENT','PARTIALLY_FILLED','UNKNOWN')"
        ),
    )
    op.create_table(
        "venue_fills",
        sa.Column("venue_fill_fact_id", sa.Uuid(), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("venue_fill_id", sa.String(length=255), nullable=False),
        sa.Column("order_intent_id", sa.Uuid(), nullable=True),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("account_id", sa.String(length=120), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("fee", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("fee_currency", sa.String(length=32), nullable=False),
        sa.Column("slippage_cost", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("side IN ('BUY','SELL')", name="ck_venue_fills_side"),
        sa.CheckConstraint(
            "environment IN ('SHADOW','TESTNET','LIVE')",
            name="ck_venue_fills_environment",
        ),
        sa.CheckConstraint("fee >= 0", name="ck_venue_fills_fee_nonnegative"),
        sa.CheckConstraint("price > 0", name="ck_venue_fills_price_positive"),
        sa.CheckConstraint("quantity > 0", name="ck_venue_fills_quantity_positive"),
        sa.CheckConstraint("slippage_cost >= 0", name="ck_venue_fills_slippage_nonnegative"),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.campaign_id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.instrument_id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_intent_id"],
            ["order_intents.intent_id"],
        ),
        sa.PrimaryKeyConstraint("venue_fill_fact_id"),
        sa.UniqueConstraint(
            "environment",
            "account_id",
            "venue",
            "venue_fill_id",
            name="uq_venue_fills_external",
        ),
    )
    op.create_index(
        "ix_venue_fills_campaign_time", "venue_fills", ["campaign_id", "executed_at"], unique=False
    )
    op.create_index(
        "ix_venue_fills_scope",
        "venue_fills",
        ["environment", "account_id", "venue", "instrument_id"],
        unique=False,
    )
    op.create_table(
        "venue_orders",
        sa.Column("venue_order_fact_id", sa.Uuid(), nullable=False),
        sa.Column("order_intent_id", sa.Uuid(), nullable=True),
        sa.Column("account_id", sa.String(length=120), nullable=False),
        sa.Column("venue", sa.String(length=64), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("venue_order_id", sa.String(length=255), nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("order_type", sa.String(length=32), nullable=False),
        sa.Column("reduce_only", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("ordered_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("filled_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('SENT','PARTIALLY_FILLED','FILLED','CANCELLED','REJECTED','UNKNOWN')",
            name="ck_venue_orders_status",
        ),
        sa.CheckConstraint(
            "environment IN ('SHADOW','TESTNET','LIVE')",
            name="ck_venue_orders_environment",
        ),
        sa.CheckConstraint("side IN ('BUY','SELL')", name="ck_venue_orders_side"),
        sa.CheckConstraint("filled_quantity >= 0", name="ck_venue_orders_filled_nonnegative"),
        sa.CheckConstraint("ordered_quantity >= 0", name="ck_venue_orders_quantity_nonnegative"),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.instrument_id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_intent_id"],
            ["order_intents.intent_id"],
        ),
        sa.PrimaryKeyConstraint("venue_order_fact_id"),
        sa.UniqueConstraint("order_intent_id", name="uq_venue_orders_intent"),
        sa.UniqueConstraint(
            "environment",
            "account_id",
            "venue",
            "client_order_id",
            name="uq_venue_orders_client_identity",
        ),
        sa.UniqueConstraint(
            "environment",
            "account_id",
            "venue",
            "venue_order_id",
            name="uq_venue_orders_external",
        ),
    )
    op.create_index(
        "ix_venue_orders_scope",
        "venue_orders",
        ["environment", "account_id", "venue", "instrument_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_venue_orders_scope", table_name="venue_orders")
    op.drop_table("venue_orders")
    op.drop_index("ix_venue_fills_scope", table_name="venue_fills")
    op.drop_index("ix_venue_fills_campaign_time", table_name="venue_fills")
    op.drop_table("venue_fills")
    op.drop_index(
        "uq_order_intents_one_active_campaign",
        table_name="order_intents",
        postgresql_where=sa.text(
            "status IN ('PENDING','RESERVED','READY','SENT','PARTIALLY_FILLED','UNKNOWN')"
        ),
    )
    op.drop_index("ix_order_intents_campaign_status", table_name="order_intents")
    op.drop_table("order_intents")
    op.drop_index("ix_risk_reservations_campaign_status", table_name="risk_reservations")
    op.drop_table("risk_reservations")
    op.drop_index("ix_reconciliation_scope_completed", table_name="reconciliation_runs")
    op.drop_table("reconciliation_runs")
    op.drop_index("ix_funding_payments_scope", table_name="funding_payments")
    op.drop_index("ix_funding_payments_campaign_time", table_name="funding_payments")
    op.drop_table("funding_payments")
    op.drop_table("campaigns")
    op.drop_table("trading_authorizations")
    op.drop_index("ix_risk_decisions_proposal_created", table_name="risk_decisions")
    op.drop_table("risk_decisions")
    op.drop_table("protection_orders")
    op.drop_index("ix_capital_transfers_status_updated", table_name="capital_transfers")
    op.drop_table("capital_transfers")
    op.drop_table("transfer_authorizations")
    op.drop_index(
        "uq_approvals_transfer_reviewer",
        table_name="approvals",
        postgresql_where=sa.text("transfer_proposal_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_approvals_proposal_reviewer",
        table_name="approvals",
        postgresql_where=sa.text("proposal_id IS NOT NULL"),
    )
    op.drop_table("approvals")
    op.drop_index("ix_role_assignments_user", table_name="role_assignments")
    op.drop_table("role_assignments")
    op.drop_index("ix_transfer_proposals_status_expires", table_name="transfer_proposals")
    op.drop_table("transfer_proposals")
    op.drop_index(
        "uq_proposals_system_candidate",
        table_name="proposals",
        postgresql_where=sa.text("source = 'SYSTEM' AND source_candidate_id IS NOT NULL"),
    )
    op.drop_index("ix_proposals_status_expires", table_name="proposals")
    op.drop_table("proposals")
    op.drop_table("positions")
    op.drop_table("users")
    op.drop_table("sender_leases")
    op.drop_index(
        "uq_risk_policies_one_active",
        table_name="risk_policies",
        postgresql_where=sa.text("active"),
    )
    op.drop_table("risk_policies")
    op.drop_table("instruments")
    op.drop_table("command_receipts")
    op.drop_table("capability_gates")
    op.drop_index("ix_audit_events_object", table_name="audit_events")
    op.drop_index("ix_audit_events_correlation", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("account_equities")
    # ### end Alembic commands ###
