# ruff: noqa: E501
"""Add atomic risk reservation and non-dispatchable shadow OrderIntent.

Revision ID: 20260718_0006
Revises: 20260718_0005
Create Date: 2026-07-18
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260718_0006"
down_revision: str | None = "20260718_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_add_packages_identity_binding",
        "add_authorization_packages",
        ["add_package_id", "campaign_id", "authorization_id"],
    )
    op.create_unique_constraint(
        "uq_add_units_identity_binding",
        "add_units",
        ["add_unit_id", "add_package_id"],
    )
    op.create_unique_constraint(
        "uq_initial_auth_identity_binding",
        "initial_order_authorizations",
        ["initial_authorization_id", "campaign_id", "authorization_id"],
    )
    op.create_table(
        "execution_risk_decisions",
        sa.Column("execution_risk_decision_id", sa.Uuid(), nullable=False),
        sa.Column("decision_stage", sa.String(length=40), nullable=False),
        sa.Column("intent_kind", sa.String(length=20), nullable=False),
        sa.Column("organization_id", sa.String(length=120), nullable=False),
        sa.Column("authorization_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("initial_authorization_id", sa.Uuid(), nullable=True),
        sa.Column("add_package_id", sa.Uuid(), nullable=True),
        sa.Column("add_unit_id", sa.Uuid(), nullable=True),
        sa.Column("risk_policy_id", sa.Uuid(), nullable=False),
        sa.Column("risk_policy_version", sa.String(length=120), nullable=False),
        sa.Column("system_risk_state", sa.String(length=32), nullable=False),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("primary_reason_code", sa.String(length=160), nullable=False),
        sa.Column("requested_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("max_safe_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("final_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("approved_reserved_heat", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("approved_funding", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("approved_margin", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column(
            "current_portfolio_mtm_equity", sa.Numeric(precision=38, scale=18), nullable=False
        ),
        sa.Column("current_unrealized_pnl", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("decision", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decision_hash", sa.String(length=64), nullable=False),
        sa.Column("execution_eligible", sa.Boolean(), nullable=False),
        sa.Column("reservation_created", sa.Boolean(), nullable=False),
        sa.Column("order_intent_created", sa.Boolean(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(intent_kind = 'INITIAL' AND initial_authorization_id IS NOT NULL AND add_package_id IS NULL AND add_unit_id IS NULL) OR (intent_kind = 'ADD' AND initial_authorization_id IS NULL AND add_package_id IS NOT NULL AND add_unit_id IS NOT NULL)",
            name="ck_exec_risk_authorization_kind",
        ),
        sa.CheckConstraint(
            "(result = 'ALLOW' AND max_safe_quantity = requested_quantity AND final_quantity = requested_quantity AND approved_reserved_heat > 0 AND reservation_created = true AND order_intent_created = true AND valid_until > decided_at) OR (result = 'DENY' AND final_quantity = 0 AND approved_reserved_heat = 0 AND approved_funding = 0 AND approved_margin = 0 AND reservation_created = false AND order_intent_created = false AND valid_until = decided_at)",
            name="ck_exec_risk_result_contract",
        ),
        sa.CheckConstraint("decision_stage = 'ORDER_PRECHECK'", name="ck_exec_risk_stage"),
        sa.CheckConstraint("intent_kind IN ('INITIAL', 'ADD')", name="ck_exec_risk_intent_kind"),
        sa.CheckConstraint(
            "length(input_hash) = 64 AND length(decision_hash) = 64 AND jsonb_typeof(input_snapshot) = 'object' AND jsonb_typeof(decision) = 'object'",
            name="ck_exec_risk_snapshot_integrity",
        ),
        sa.CheckConstraint("result IN ('ALLOW', 'DENY')", name="ck_exec_risk_result"),
        sa.CheckConstraint(
            "system_risk_state IN ('NORMAL', 'NO_PYRAMID', 'NO_NEW_POSITION', 'REDUCE_ONLY', 'KILL_SWITCH', 'UNKNOWN')",
            name="ck_exec_risk_system_state",
        ),
        sa.CheckConstraint(
            "approved_reserved_heat >= 0 AND approved_funding >= 0 AND approved_margin >= 0 AND current_portfolio_mtm_equity IS NOT NULL AND current_unrealized_pnl IS NOT NULL",
            name="ck_exec_risk_amounts",
        ),
        sa.CheckConstraint("execution_eligible = false", name="ck_exec_risk_shadow_only"),
        sa.CheckConstraint(
            "requested_quantity > 0 AND max_safe_quantity >= 0 AND final_quantity >= 0 AND max_safe_quantity <= requested_quantity AND final_quantity <= requested_quantity",
            name="ck_exec_risk_quantity_bounds",
        ),
        sa.ForeignKeyConstraint(
            ["add_package_id", "campaign_id", "authorization_id"],
            [
                "add_authorization_packages.add_package_id",
                "add_authorization_packages.campaign_id",
                "add_authorization_packages.authorization_id",
            ],
            name="fk_exec_risk_add_package_binding",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["add_unit_id", "add_package_id"],
            ["add_units.add_unit_id", "add_units.add_package_id"],
            name="fk_exec_risk_add_unit_binding",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id", "authorization_id"],
            ["campaigns.campaign_id", "campaigns.authorization_id"],
            name="fk_exec_risk_campaign_authorization",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["initial_authorization_id", "campaign_id", "authorization_id"],
            [
                "initial_order_authorizations.initial_authorization_id",
                "initial_order_authorizations.campaign_id",
                "initial_order_authorizations.authorization_id",
            ],
            name="fk_exec_risk_initial_binding",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["risk_policy_id", "organization_id", "risk_policy_version"],
            [
                "risk_policies.risk_policy_id",
                "risk_policies.organization_id",
                "risk_policies.policy_version",
            ],
            name="fk_exec_risk_policy_binding",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("execution_risk_decision_id"),
    )
    op.create_index(
        "ix_exec_risk_campaign_time",
        "execution_risk_decisions",
        ["campaign_id", "decided_at"],
        unique=False,
    )
    op.create_table(
        "order_intents",
        sa.Column("order_intent_id", sa.Uuid(), nullable=False),
        sa.Column("execution_risk_decision_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_version_id", sa.Uuid(), nullable=False),
        sa.Column("authorization_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("initial_authorization_id", sa.Uuid(), nullable=True),
        sa.Column("add_package_id", sa.Uuid(), nullable=True),
        sa.Column("add_unit_id", sa.Uuid(), nullable=True),
        sa.Column("intent_kind", sa.String(length=20), nullable=False),
        sa.Column("candidate_ref", sa.String(length=255), nullable=False),
        sa.Column("candidate_hash", sa.String(length=64), nullable=False),
        sa.Column("strategy_owner", sa.String(length=160), nullable=False),
        sa.Column("venue", sa.String(length=80), nullable=False),
        sa.Column("execution_domain", sa.String(length=120), nullable=False),
        sa.Column("account_id", sa.String(length=160), nullable=False),
        sa.Column("worker_id", sa.String(length=160), nullable=False),
        sa.Column("instrument_id", sa.String(length=255), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("position_side", sa.String(length=20), nullable=False),
        sa.Column("reduce_only", sa.Boolean(), nullable=False),
        sa.Column("current_position_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("target_position_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("expected_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("max_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("quantity_source", sa.String(length=40), nullable=False),
        sa.Column("order_type", sa.String(length=40), nullable=False),
        sa.Column("time_in_force", sa.String(length=40), nullable=False),
        sa.Column("trigger_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("limit_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("price_reference", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("price_lower_bound", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("price_upper_bound", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("max_slippage_bps", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("risk_currency", sa.String(length=80), nullable=False),
        sa.Column("margin_mode", sa.String(length=80), nullable=False),
        sa.Column("collateral_scope", sa.String(length=120), nullable=False),
        sa.Column("collateral_pool_id", sa.String(length=160), nullable=False),
        sa.Column("capability_certificate_ref", sa.String(length=255), nullable=False),
        sa.Column("execution_mode", sa.String(length=20), nullable=False),
        sa.Column("dispatch_eligible", sa.Boolean(), nullable=False),
        sa.Column("intent_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("intent_snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(intent_kind = 'INITIAL' AND initial_authorization_id IS NOT NULL AND add_package_id IS NULL AND add_unit_id IS NULL AND quantity_source = 'INITIAL_RISK_APPROVED') OR (intent_kind = 'ADD' AND initial_authorization_id IS NULL AND add_package_id IS NOT NULL AND add_unit_id IS NOT NULL AND quantity_source = 'TARGET_LEVERAGE_DELTA')",
            name="ck_order_intents_authorization_kind",
        ),
        sa.CheckConstraint(
            "execution_mode = 'SHADOW' AND dispatch_eligible = false",
            name="ck_order_intents_shadow_only",
        ),
        sa.CheckConstraint("intent_kind IN ('INITIAL', 'ADD')", name="ck_order_intents_kind"),
        sa.CheckConstraint(
            "length(candidate_hash) = 64 AND length(intent_snapshot_hash) = 64 AND jsonb_typeof(intent_snapshot) = 'object'",
            name="ck_order_intents_hashes",
        ),
        sa.CheckConstraint(
            "position_side IN ('LONG', 'SHORT')", name="ck_order_intents_position_side"
        ),
        sa.CheckConstraint(
            "quantity_source IN ('INITIAL_RISK_APPROVED', 'TARGET_LEVERAGE_DELTA')",
            name="ck_order_intents_quantity_source",
        ),
        sa.CheckConstraint("side IN ('BUY', 'SELL')", name="ck_order_intents_side"),
        sa.CheckConstraint(
            "current_position_quantity >= 0 AND target_position_quantity > 0 AND expected_quantity > 0 AND max_quantity >= expected_quantity AND target_position_quantity - current_position_quantity >= expected_quantity",
            name="ck_order_intents_quantity_contract",
        ),
        sa.CheckConstraint(
            "price_reference > 0 AND price_lower_bound > 0 AND price_upper_bound >= price_lower_bound AND price_reference BETWEEN price_lower_bound AND price_upper_bound AND max_slippage_bps >= 0",
            name="ck_order_intents_price_contract",
        ),
        sa.CheckConstraint("reduce_only = false", name="ck_order_intents_increase_only"),
        sa.CheckConstraint("valid_until > valid_from", name="ck_order_intents_valid_window"),
        sa.ForeignKeyConstraint(
            ["add_package_id", "campaign_id", "authorization_id"],
            [
                "add_authorization_packages.add_package_id",
                "add_authorization_packages.campaign_id",
                "add_authorization_packages.authorization_id",
            ],
            name="fk_order_intents_add_package_binding",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["add_unit_id", "add_package_id"],
            ["add_units.add_unit_id", "add_units.add_package_id"],
            name="fk_order_intents_add_unit_binding",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id", "authorization_id"],
            ["campaigns.campaign_id", "campaigns.authorization_id"],
            name="fk_order_intents_campaign_authorization",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["execution_risk_decision_id"],
            ["execution_risk_decisions.execution_risk_decision_id"],
            name="fk_order_intents_risk_decision",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["initial_authorization_id", "campaign_id", "authorization_id"],
            [
                "initial_order_authorizations.initial_authorization_id",
                "initial_order_authorizations.campaign_id",
                "initial_order_authorizations.authorization_id",
            ],
            name="fk_order_intents_initial_binding",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("order_intent_id"),
        sa.UniqueConstraint("campaign_id", "candidate_ref", name="uq_order_intents_candidate"),
        sa.UniqueConstraint("execution_risk_decision_id", name="uq_order_intents_risk_decision"),
        sa.UniqueConstraint(
            "order_intent_id",
            "campaign_id",
            "authorization_id",
            name="uq_order_intents_identity_binding",
        ),
    )
    op.create_index(
        "ix_order_intents_campaign_created",
        "order_intents",
        ["campaign_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_order_intents_execution_route",
        "order_intents",
        ["venue", "execution_domain", "account_id"],
        unique=False,
    )
    op.create_table(
        "execution_facts",
        sa.Column("execution_fact_id", sa.Uuid(), nullable=False),
        sa.Column("order_intent_id", sa.Uuid(), nullable=False),
        sa.Column("fact_sequence", sa.Integer(), nullable=False),
        sa.Column("target_status", sa.String(length=32), nullable=False),
        sa.Column("venue", sa.String(length=80), nullable=False),
        sa.Column("execution_domain", sa.String(length=120), nullable=False),
        sa.Column("account_id", sa.String(length=160), nullable=False),
        sa.Column("external_fact_id", sa.String(length=255), nullable=False),
        sa.Column("cumulative_filled_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("known_remaining_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("zero_fill_confirmed", sa.Boolean(), nullable=False),
        sa.Column("venue_order_terminal", sa.Boolean(), nullable=False),
        sa.Column("position_reconciled", sa.Boolean(), nullable=False),
        sa.Column("protection_confirmed", sa.Boolean(), nullable=False),
        sa.Column("reconciliation_run_ref", sa.String(length=255), nullable=True),
        sa.Column("source_ref", sa.String(length=255), nullable=False),
        sa.Column("source_version", sa.String(length=120), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("evidence_ref", sa.String(length=255), nullable=False),
        sa.Column("evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "target_status IN ('INTENT_CREATED', 'DISPATCHING', 'VENUE_ACKNOWLEDGED', 'PARTIALLY_FILLED', 'FILLED', 'CANCEL_PENDING', 'CANCELLED_ZERO_FILL', 'CANCELLED_PARTIAL', 'REJECTED_ZERO_FILL', 'RESULT_UNKNOWN', 'POSITION_RECONCILED', 'PROTECTION_CONFIRMED', 'COMPLETED', 'FAILED_SAFE')",
            name="ck_execution_facts_status",
        ),
        sa.CheckConstraint(
            "cumulative_filled_quantity >= 0 AND known_remaining_quantity >= 0",
            name="ck_execution_facts_quantities",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object' AND event_time <= received_at AND received_at <= recorded_at",
            name="ck_execution_facts_evidence_contract",
        ),
        sa.CheckConstraint("fact_sequence >= 1", name="ck_execution_facts_sequence"),
        sa.CheckConstraint(
            "length(payload_hash) = 64 AND length(evidence_hash) = 64",
            name="ck_execution_facts_hashes",
        ),
        sa.ForeignKeyConstraint(
            ["order_intent_id"], ["order_intents.order_intent_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("execution_fact_id"),
        sa.UniqueConstraint(
            "order_intent_id", "fact_sequence", name="uq_execution_facts_intent_sequence"
        ),
        sa.UniqueConstraint(
            "venue",
            "execution_domain",
            "account_id",
            "external_fact_id",
            name="uq_execution_facts_external_identity",
        ),
    )
    op.create_index(
        "ix_execution_facts_intent_time",
        "execution_facts",
        ["order_intent_id", "event_time"],
        unique=False,
    )
    op.create_table(
        "order_intent_state_history",
        sa.Column("history_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_intent_id", sa.Uuid(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("state_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("reason_code", sa.String(length=160), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(state_snapshot) = 'object' AND length(state_hash) = 64",
            name="ck_order_intent_history_snapshot",
        ),
        sa.CheckConstraint("state_version >= 1", name="ck_order_intent_history_version"),
        sa.ForeignKeyConstraint(
            ["order_intent_id"], ["order_intents.order_intent_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("history_id"),
        sa.UniqueConstraint(
            "order_intent_id", "state_version", name="uq_order_intent_history_version"
        ),
    )
    op.create_table(
        "order_intent_states",
        sa.Column("order_intent_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("intent_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("cumulative_filled_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("known_remaining_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("zero_fill_confirmed", sa.Boolean(), nullable=False),
        sa.Column("venue_order_terminal", sa.Boolean(), nullable=False),
        sa.Column("position_reconciled", sa.Boolean(), nullable=False),
        sa.Column("protection_confirmed", sa.Boolean(), nullable=False),
        sa.Column("last_fact_sequence", sa.Integer(), nullable=False),
        sa.Column("last_fact_hash", sa.String(length=64), nullable=True),
        sa.Column("reason_code", sa.String(length=160), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('INTENT_CREATED', 'DISPATCHING', 'VENUE_ACKNOWLEDGED', 'PARTIALLY_FILLED', 'FILLED', 'CANCEL_PENDING', 'CANCELLED_ZERO_FILL', 'CANCELLED_PARTIAL', 'REJECTED_ZERO_FILL', 'RESULT_UNKNOWN', 'POSITION_RECONCILED', 'PROTECTION_CONFIRMED', 'COMPLETED', 'FAILED_SAFE')",
            name="ck_order_intent_states_status",
        ),
        sa.CheckConstraint(
            "(last_fact_sequence = 0 AND last_fact_hash IS NULL) OR (last_fact_sequence > 0 AND length(last_fact_hash) = 64)",
            name="ck_order_intent_states_fact_binding",
        ),
        sa.CheckConstraint(
            "intent_quantity > 0 AND cumulative_filled_quantity >= 0 AND known_remaining_quantity >= 0 AND cumulative_filled_quantity <= intent_quantity AND known_remaining_quantity <= intent_quantity",
            name="ck_order_intent_states_quantities",
        ),
        sa.CheckConstraint("version >= 1", name="ck_order_intent_states_version"),
        sa.ForeignKeyConstraint(
            ["order_intent_id"], ["order_intents.order_intent_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("order_intent_id"),
    )
    op.create_table(
        "risk_reservations",
        sa.Column("risk_reservation_id", sa.Uuid(), nullable=False),
        sa.Column("execution_risk_decision_id", sa.Uuid(), nullable=False),
        sa.Column("order_intent_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.String(length=120), nullable=False),
        sa.Column("authorization_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("initial_authorization_id", sa.Uuid(), nullable=True),
        sa.Column("add_package_id", sa.Uuid(), nullable=True),
        sa.Column("add_unit_id", sa.Uuid(), nullable=True),
        sa.Column("intent_kind", sa.String(length=20), nullable=False),
        sa.Column("account_id", sa.String(length=160), nullable=False),
        sa.Column("instrument_id", sa.String(length=255), nullable=False),
        sa.Column("collateral_pool_id", sa.String(length=160), nullable=False),
        sa.Column("risk_currency", sa.String(length=80), nullable=False),
        sa.Column("valuation_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("valuation_price_source_ref", sa.String(length=255), nullable=False),
        sa.Column("reserved_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("reserved_heat", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("funding_reserved", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("margin_reserved", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("scope_allocations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(intent_kind = 'INITIAL' AND initial_authorization_id IS NOT NULL AND add_package_id IS NULL AND add_unit_id IS NULL) OR (intent_kind = 'ADD' AND initial_authorization_id IS NULL AND add_package_id IS NOT NULL AND add_unit_id IS NOT NULL)",
            name="ck_risk_reservations_authorization_kind",
        ),
        sa.CheckConstraint("intent_kind IN ('INITIAL', 'ADD')", name="ck_risk_reservations_kind"),
        sa.CheckConstraint(
            "jsonb_typeof(scope_allocations) = 'array' AND jsonb_array_length(scope_allocations) = 7",
            name="ck_risk_reservations_scope_allocations",
        ),
        sa.CheckConstraint(
            "reserved_quantity > 0 AND reserved_heat > 0 AND funding_reserved >= 0 AND margin_reserved >= 0",
            name="ck_risk_reservations_amounts",
        ),
        sa.CheckConstraint("valid_until > created_at", name="ck_risk_reservations_valid_window"),
        sa.ForeignKeyConstraint(
            ["add_package_id", "campaign_id", "authorization_id"],
            [
                "add_authorization_packages.add_package_id",
                "add_authorization_packages.campaign_id",
                "add_authorization_packages.authorization_id",
            ],
            name="fk_risk_reservations_add_package_binding",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["add_unit_id", "add_package_id"],
            ["add_units.add_unit_id", "add_units.add_package_id"],
            name="fk_risk_reservations_add_unit_binding",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id", "authorization_id"],
            ["campaigns.campaign_id", "campaigns.authorization_id"],
            name="fk_risk_reservations_campaign_authorization",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["execution_risk_decision_id"],
            ["execution_risk_decisions.execution_risk_decision_id"],
            name="fk_risk_reservations_risk_decision",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["initial_authorization_id", "campaign_id", "authorization_id"],
            [
                "initial_order_authorizations.initial_authorization_id",
                "initial_order_authorizations.campaign_id",
                "initial_order_authorizations.authorization_id",
            ],
            name="fk_risk_reservations_initial_binding",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_intent_id", "campaign_id", "authorization_id"],
            [
                "order_intents.order_intent_id",
                "order_intents.campaign_id",
                "order_intents.authorization_id",
            ],
            name="fk_risk_reservations_order_binding",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("risk_reservation_id"),
        sa.UniqueConstraint(
            "execution_risk_decision_id", name="uq_risk_reservations_risk_decision"
        ),
        sa.UniqueConstraint("order_intent_id", name="uq_risk_reservations_order_intent"),
    )
    op.create_index(
        "ix_risk_reservations_org_created",
        "risk_reservations",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "risk_exposure_state_history",
        sa.Column("history_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("risk_reservation_id", sa.Uuid(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("state_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("reason_code", sa.String(length=160), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(state_snapshot) = 'object' AND length(state_hash) = 64",
            name="ck_risk_exposure_history_snapshot",
        ),
        sa.CheckConstraint("state_version >= 1", name="ck_risk_exposure_history_version"),
        sa.ForeignKeyConstraint(
            ["risk_reservation_id"], ["risk_reservations.risk_reservation_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("history_id"),
        sa.UniqueConstraint(
            "risk_reservation_id", "state_version", name="uq_risk_exposure_history_version"
        ),
    )
    op.create_table(
        "risk_exposure_states",
        sa.Column("risk_reservation_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("ledger_sequence", sa.Integer(), nullable=False),
        sa.Column("total_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("reserved_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("open_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("unknown_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("released_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("total_heat", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("reserved_heat", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("open_heat", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("unknown_heat", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("released_heat", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("total_funding", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("funding_reserved", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("funding_used", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("funding_unknown", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("funding_released", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("total_margin", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("margin_reserved", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("margin_used", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("margin_unknown", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("margin_released", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("last_evidence_ref", sa.String(length=255), nullable=False),
        sa.Column("last_evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("reason_code", sa.String(length=160), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('RESERVED', 'PARTIAL', 'UNKNOWN', 'OPEN', 'RELEASED')",
            name="ck_risk_exposure_states_status",
        ),
        sa.CheckConstraint(
            "funding_reserved >= 0 AND funding_used >= 0 AND funding_unknown >= 0 AND funding_released >= 0 AND funding_reserved + funding_used + funding_unknown + funding_released = total_funding",
            name="ck_risk_exposure_funding_conservation",
        ),
        sa.CheckConstraint("length(last_evidence_hash) = 64", name="ck_risk_exposure_evidence"),
        sa.CheckConstraint(
            "margin_reserved >= 0 AND margin_used >= 0 AND margin_unknown >= 0 AND margin_released >= 0 AND margin_reserved + margin_used + margin_unknown + margin_released = total_margin",
            name="ck_risk_exposure_margin_conservation",
        ),
        sa.CheckConstraint(
            "reserved_heat >= 0 AND open_heat >= 0 AND unknown_heat >= 0 AND released_heat >= 0 AND reserved_heat + open_heat + unknown_heat + released_heat = total_heat",
            name="ck_risk_exposure_heat_conservation",
        ),
        sa.CheckConstraint(
            "reserved_quantity >= 0 AND open_quantity >= 0 AND unknown_quantity >= 0 AND released_quantity >= 0 AND reserved_quantity + open_quantity + unknown_quantity + released_quantity = total_quantity",
            name="ck_risk_exposure_quantity_conservation",
        ),
        sa.CheckConstraint(
            "total_quantity > 0 AND total_heat > 0 AND total_funding >= 0 AND total_margin >= 0",
            name="ck_risk_exposure_totals",
        ),
        sa.CheckConstraint(
            "version >= 1 AND ledger_sequence >= 1", name="ck_risk_exposure_version"
        ),
        sa.ForeignKeyConstraint(
            ["risk_reservation_id"], ["risk_reservations.risk_reservation_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("risk_reservation_id"),
    )
    op.create_table(
        "risk_ledger_entries",
        sa.Column("risk_ledger_entry_id", sa.Uuid(), nullable=False),
        sa.Column("risk_reservation_id", sa.Uuid(), nullable=False),
        sa.Column("order_intent_id", sa.Uuid(), nullable=False),
        sa.Column("execution_fact_id", sa.Uuid(), nullable=True),
        sa.Column("entry_sequence", sa.Integer(), nullable=False),
        sa.Column("entry_type", sa.String(length=20), nullable=False),
        sa.Column("from_bucket", sa.String(length=20), nullable=False),
        sa.Column("to_bucket", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("heat", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("funding", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("margin", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("evidence_ref", sa.String(length=255), nullable=False),
        sa.Column("evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "entry_type IN ('RESERVE', 'MIGRATE', 'RELEASE')", name="ck_risk_ledger_entries_type"
        ),
        sa.CheckConstraint(
            "from_bucket IN ('AUTHORIZED', 'RESERVED', 'OPEN', 'UNKNOWN', 'RELEASED') AND to_bucket IN ('AUTHORIZED', 'RESERVED', 'OPEN', 'UNKNOWN', 'RELEASED') AND from_bucket <> to_bucket",
            name="ck_risk_ledger_entries_buckets",
        ),
        sa.CheckConstraint("length(evidence_hash) = 64", name="ck_risk_ledger_entries_evidence"),
        sa.CheckConstraint(
            "quantity > 0 AND heat > 0 AND funding >= 0 AND margin >= 0",
            name="ck_risk_ledger_entries_amounts",
        ),
        sa.ForeignKeyConstraint(
            ["execution_fact_id"], ["execution_facts.execution_fact_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["order_intent_id"], ["order_intents.order_intent_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["risk_reservation_id"], ["risk_reservations.risk_reservation_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("risk_ledger_entry_id"),
        sa.UniqueConstraint(
            "risk_reservation_id", "entry_sequence", name="uq_risk_ledger_entry_sequence"
        ),
    )
    op.create_index(
        "ix_risk_ledger_entries_intent_time",
        "risk_ledger_entries",
        ["order_intent_id", "occurred_at"],
        unique=False,
    )
    _create_integrity_guards()
    # ### end Alembic commands ###


def downgrade() -> None:
    _drop_integrity_guards()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_risk_ledger_entries_intent_time", table_name="risk_ledger_entries")
    op.drop_table("risk_ledger_entries")
    op.drop_table("risk_exposure_states")
    op.drop_table("risk_exposure_state_history")
    op.drop_index("ix_risk_reservations_org_created", table_name="risk_reservations")
    op.drop_table("risk_reservations")
    op.drop_table("order_intent_states")
    op.drop_table("order_intent_state_history")
    op.drop_index("ix_execution_facts_intent_time", table_name="execution_facts")
    op.drop_table("execution_facts")
    op.drop_index("ix_order_intents_execution_route", table_name="order_intents")
    op.drop_index("ix_order_intents_campaign_created", table_name="order_intents")
    op.drop_table("order_intents")
    op.drop_index("ix_exec_risk_campaign_time", table_name="execution_risk_decisions")
    op.drop_table("execution_risk_decisions")
    op.drop_constraint(
        "uq_initial_auth_identity_binding", "initial_order_authorizations", type_="unique"
    )
    op.drop_constraint("uq_add_units_identity_binding", "add_units", type_="unique")
    op.drop_constraint(
        "uq_add_packages_identity_binding", "add_authorization_packages", type_="unique"
    )
    # ### end Alembic commands ###


def _create_integrity_guards() -> None:
    op.execute(
        """
        CREATE FUNCTION deny_execution_fact_change()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% is immutable', TG_TABLE_NAME;
        END;
        $$
        """
    )
    for table in (
        "execution_risk_decisions",
        "order_intents",
        "execution_facts",
        "risk_reservations",
        "risk_ledger_entries",
        "order_intent_state_history",
        "risk_exposure_state_history",
    ):
        op.execute(
            f"""
            CREATE TRIGGER {table}_immutable
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION deny_execution_fact_change()
            """
        )

    op.execute(
        """
        CREATE FUNCTION verify_execution_atomic_graph()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE decision_row execution_risk_decisions%ROWTYPE;
        DECLARE intent_row order_intents%ROWTYPE;
        DECLARE reservation_row risk_reservations%ROWTYPE;
        DECLARE decision_key uuid;
        DECLARE intent_count integer;
        DECLARE reservation_count integer;
        DECLARE intent_state_count integer;
        DECLARE exposure_state_count integer;
        DECLARE reserve_ledger_count integer;
        DECLARE authorization_state text;
        BEGIN
            IF TG_TABLE_NAME = 'execution_risk_decisions' THEN
                decision_key := NEW.execution_risk_decision_id;
            ELSIF TG_TABLE_NAME = 'order_intents' THEN
                decision_key := NEW.execution_risk_decision_id;
            ELSE
                decision_key := NEW.execution_risk_decision_id;
            END IF;

            SELECT * INTO STRICT decision_row FROM execution_risk_decisions
            WHERE execution_risk_decision_id = decision_key;
            SELECT count(*) INTO intent_count FROM order_intents
            WHERE execution_risk_decision_id = decision_key;
            SELECT count(*) INTO reservation_count FROM risk_reservations
            WHERE execution_risk_decision_id = decision_key;

            IF decision_row.result = 'DENY' THEN
                IF intent_count <> 0 OR reservation_count <> 0 THEN
                    RAISE EXCEPTION 'DENY decision cannot own intent or reservation';
                END IF;
                RETURN NEW;
            END IF;
            IF intent_count <> 1 OR reservation_count <> 1 THEN
                RAISE EXCEPTION 'ALLOW decision requires exactly one intent and reservation';
            END IF;

            SELECT * INTO STRICT intent_row FROM order_intents
            WHERE execution_risk_decision_id = decision_key;
            SELECT * INTO STRICT reservation_row FROM risk_reservations
            WHERE execution_risk_decision_id = decision_key;
            SELECT count(*) INTO intent_state_count FROM order_intent_states
            WHERE order_intent_id = intent_row.order_intent_id;
            SELECT count(*) INTO exposure_state_count FROM risk_exposure_states
            WHERE risk_reservation_id = reservation_row.risk_reservation_id;
            SELECT count(*) INTO reserve_ledger_count FROM risk_ledger_entries
            WHERE risk_reservation_id = reservation_row.risk_reservation_id
              AND entry_sequence = 1 AND entry_type = 'RESERVE'
              AND from_bucket = 'AUTHORIZED' AND to_bucket = 'RESERVED'
              AND quantity = reservation_row.reserved_quantity
              AND heat = reservation_row.reserved_heat
              AND funding = reservation_row.funding_reserved
              AND margin = reservation_row.margin_reserved;
            IF reservation_row.order_intent_id <> intent_row.order_intent_id
                OR reservation_row.authorization_id <> decision_row.authorization_id
                OR reservation_row.campaign_id <> decision_row.campaign_id
                OR reservation_row.intent_kind <> decision_row.intent_kind
                OR intent_row.authorization_id <> decision_row.authorization_id
                OR intent_row.campaign_id <> decision_row.campaign_id
                OR intent_row.intent_kind <> decision_row.intent_kind
                OR reservation_row.reserved_quantity <> decision_row.final_quantity
                OR intent_row.expected_quantity <> decision_row.final_quantity
                OR reservation_row.reserved_heat <> decision_row.approved_reserved_heat
                OR reservation_row.funding_reserved <> decision_row.approved_funding
                OR reservation_row.margin_reserved <> decision_row.approved_margin
                OR reservation_row.valid_until <> decision_row.valid_until
                OR intent_row.valid_until <> decision_row.valid_until
                OR intent_state_count <> 1
                OR exposure_state_count <> 1
                OR reserve_ledger_count <> 1 THEN
                RAISE EXCEPTION 'execution decision, intent, and reservation bindings disagree';
            END IF;
            IF decision_row.intent_kind = 'ADD' THEN
                SELECT status INTO STRICT authorization_state FROM add_unit_states
                WHERE add_unit_id = decision_row.add_unit_id;
                IF authorization_state <> 'CLAIMED' THEN
                    RAISE EXCEPTION 'ADD decision requires atomically claimed AddUnit';
                END IF;
            ELSE
                SELECT status INTO STRICT authorization_state
                FROM initial_authorization_states
                WHERE initial_authorization_id = decision_row.initial_authorization_id;
                IF authorization_state <> 'ACTIVE' THEN
                    RAISE EXCEPTION 'INITIAL decision requires active initial authorization';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    for table in ("execution_risk_decisions", "order_intents", "risk_reservations"):
        op.execute(
            f"""
            CREATE CONSTRAINT TRIGGER {table}_atomic_graph
            AFTER INSERT ON {table}
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION verify_execution_atomic_graph()
            """
        )

    op.execute(
        """
        CREATE FUNCTION protect_order_intent_state_change()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE fact_row execution_facts%ROWTYPE;
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'order_intent_states cannot be deleted';
            END IF;
            IF NEW.order_intent_id <> OLD.order_intent_id
                OR NEW.intent_quantity <> OLD.intent_quantity
                OR NEW.version <> OLD.version + 1
                OR NEW.updated_at < OLD.updated_at
                OR NEW.last_fact_sequence <> OLD.last_fact_sequence + 1
                OR NEW.cumulative_filled_quantity < OLD.cumulative_filled_quantity THEN
                RAISE EXCEPTION 'invalid order-intent state version, identity, or monotonic facts';
            END IF;
            SELECT * INTO STRICT fact_row FROM execution_facts
            WHERE order_intent_id = NEW.order_intent_id
              AND fact_sequence = NEW.last_fact_sequence;
            IF NEW.status <> fact_row.target_status
                OR NEW.cumulative_filled_quantity <> fact_row.cumulative_filled_quantity
                OR NEW.known_remaining_quantity <> fact_row.known_remaining_quantity
                OR NEW.zero_fill_confirmed <> fact_row.zero_fill_confirmed
                OR NEW.venue_order_terminal <> fact_row.venue_order_terminal
                OR NEW.position_reconciled <> fact_row.position_reconciled
                OR NEW.protection_confirmed <> fact_row.protection_confirmed
                OR NEW.last_fact_hash <> fact_row.evidence_hash THEN
                RAISE EXCEPTION 'order-intent state does not match durable execution fact';
            END IF;
            IF NEW.cumulative_filled_quantity + NEW.known_remaining_quantity
                > NEW.intent_quantity THEN
                RAISE EXCEPTION 'execution quantities exceed intent quantity';
            END IF;
            IF NEW.zero_fill_confirmed
                AND NEW.status NOT IN ('CANCELLED_ZERO_FILL', 'REJECTED_ZERO_FILL') THEN
                RAISE EXCEPTION 'zero-fill proof cannot accompany this status';
            END IF;
            IF NEW.status IN ('CANCELLED_ZERO_FILL', 'REJECTED_ZERO_FILL')
                AND NOT (NEW.zero_fill_confirmed AND NEW.venue_order_terminal
                    AND NEW.cumulative_filled_quantity = 0
                    AND NEW.known_remaining_quantity = 0) THEN
                RAISE EXCEPTION 'zero-fill terminal state lacks proof';
            ELSIF NEW.status = 'PARTIALLY_FILLED'
                AND NOT (NEW.cumulative_filled_quantity > 0
                    AND NEW.known_remaining_quantity > 0
                    AND NOT NEW.venue_order_terminal) THEN
                RAISE EXCEPTION 'partial-fill state is inconsistent';
            ELSIF NEW.status = 'FILLED'
                AND NOT (NEW.cumulative_filled_quantity = NEW.intent_quantity
                    AND NEW.known_remaining_quantity = 0 AND NEW.venue_order_terminal) THEN
                RAISE EXCEPTION 'filled state is inconsistent';
            ELSIF NEW.status = 'CANCELLED_PARTIAL'
                AND NOT (NEW.cumulative_filled_quantity > 0
                    AND NEW.known_remaining_quantity = 0 AND NEW.venue_order_terminal) THEN
                RAISE EXCEPTION 'partial cancellation is inconsistent';
            ELSIF NEW.status = 'RESULT_UNKNOWN'
                AND NOT (NEW.known_remaining_quantity = 0 AND NOT NEW.zero_fill_confirmed) THEN
                RAISE EXCEPTION 'unknown state cannot claim known remaining or zero fill';
            ELSIF NEW.status IN ('POSITION_RECONCILED', 'PROTECTION_CONFIRMED', 'COMPLETED')
                AND NOT NEW.position_reconciled THEN
                RAISE EXCEPTION 'reconciled terminal progression lacks position fact';
            END IF;
            IF NEW.status IN ('PROTECTION_CONFIRMED', 'COMPLETED')
                AND NOT (NEW.protection_confirmed AND NEW.cumulative_filled_quantity > 0
                    AND NEW.known_remaining_quantity = 0 AND NEW.venue_order_terminal) THEN
                RAISE EXCEPTION 'protected progression lacks positive reconciled fill';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER order_intent_states_transition_guard
        BEFORE UPDATE OR DELETE ON order_intent_states
        FOR EACH ROW EXECUTE FUNCTION protect_order_intent_state_change()
        """
    )
    op.execute(
        """
        CREATE FUNCTION record_order_intent_state_change()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE snapshot jsonb;
        BEGIN
            snapshot := to_jsonb(NEW);
            INSERT INTO order_intent_state_history (
                order_intent_id, state_version, status, state_snapshot,
                state_hash, reason_code, changed_at
            ) VALUES (
                NEW.order_intent_id, NEW.version, NEW.status, snapshot,
                encode(sha256(convert_to(snapshot::text, 'UTF8')), 'hex'),
                NEW.reason_code, NEW.updated_at
            );
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER order_intent_states_record_history
        AFTER INSERT OR UPDATE ON order_intent_states
        FOR EACH ROW EXECUTE FUNCTION record_order_intent_state_change()
        """
    )

    op.execute(
        """
        CREATE FUNCTION protect_risk_exposure_state_change()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE ledger_count integer;
        DECLARE ledger_max integer;
        DECLARE ledger_ref text;
        DECLARE ledger_hash text;
        DECLARE expected_status text;
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'risk_exposure_states cannot be deleted';
            END IF;
            IF TG_OP = 'UPDATE' AND (
                NEW.risk_reservation_id <> OLD.risk_reservation_id
                OR NEW.total_quantity <> OLD.total_quantity
                OR NEW.total_heat <> OLD.total_heat
                OR NEW.total_funding <> OLD.total_funding
                OR NEW.total_margin <> OLD.total_margin
                OR NEW.version <> OLD.version + 1
                OR NEW.ledger_sequence <= OLD.ledger_sequence
                OR NEW.updated_at < OLD.updated_at) THEN
                RAISE EXCEPTION 'risk exposure root totals and versions are monotonic';
            END IF;
            SELECT count(*), max(entry_sequence) INTO ledger_count, ledger_max
            FROM risk_ledger_entries
            WHERE risk_reservation_id = NEW.risk_reservation_id;
            IF ledger_count <> NEW.ledger_sequence OR ledger_max <> NEW.ledger_sequence THEN
                RAISE EXCEPTION 'risk ledger must be gap-free and match current state';
            END IF;
            SELECT evidence_ref, evidence_hash INTO STRICT ledger_ref, ledger_hash
            FROM risk_ledger_entries
            WHERE risk_reservation_id = NEW.risk_reservation_id
              AND entry_sequence = NEW.ledger_sequence;
            IF NEW.last_evidence_ref <> ledger_ref OR NEW.last_evidence_hash <> ledger_hash THEN
                RAISE EXCEPTION 'risk exposure evidence does not match latest ledger entry';
            END IF;
            expected_status := CASE
                WHEN NEW.unknown_quantity > 0 THEN 'UNKNOWN'
                WHEN NEW.reserved_quantity > 0 AND NEW.open_quantity > 0 THEN 'PARTIAL'
                WHEN NEW.reserved_quantity > 0 THEN 'RESERVED'
                WHEN NEW.open_quantity > 0 THEN 'OPEN'
                ELSE 'RELEASED'
            END;
            IF NEW.status <> expected_status THEN
                RAISE EXCEPTION 'risk exposure status does not match conserved buckets';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER risk_exposure_states_transition_guard
        BEFORE INSERT OR UPDATE OR DELETE ON risk_exposure_states
        FOR EACH ROW EXECUTE FUNCTION protect_risk_exposure_state_change()
        """
    )
    op.execute(
        """
        CREATE FUNCTION record_risk_exposure_state_change()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE snapshot jsonb;
        BEGIN
            snapshot := to_jsonb(NEW);
            INSERT INTO risk_exposure_state_history (
                risk_reservation_id, state_version, status, state_snapshot,
                state_hash, reason_code, changed_at
            ) VALUES (
                NEW.risk_reservation_id, NEW.version, NEW.status, snapshot,
                encode(sha256(convert_to(snapshot::text, 'UTF8')), 'hex'),
                NEW.reason_code, NEW.updated_at
            );
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER risk_exposure_states_record_history
        AFTER INSERT OR UPDATE ON risk_exposure_states
        FOR EACH ROW EXECUTE FUNCTION record_risk_exposure_state_change()
        """
    )


def _drop_integrity_guards() -> None:
    op.execute("DROP TRIGGER IF EXISTS risk_exposure_states_record_history ON risk_exposure_states")
    op.execute(
        "DROP TRIGGER IF EXISTS risk_exposure_states_transition_guard ON risk_exposure_states"
    )
    op.execute("DROP FUNCTION IF EXISTS record_risk_exposure_state_change()")
    op.execute("DROP FUNCTION IF EXISTS protect_risk_exposure_state_change()")
    op.execute("DROP TRIGGER IF EXISTS order_intent_states_record_history ON order_intent_states")
    op.execute("DROP TRIGGER IF EXISTS order_intent_states_transition_guard ON order_intent_states")
    op.execute("DROP FUNCTION IF EXISTS record_order_intent_state_change()")
    op.execute("DROP FUNCTION IF EXISTS protect_order_intent_state_change()")
    for table in ("execution_risk_decisions", "order_intents", "risk_reservations"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_atomic_graph ON {table}")
    op.execute("DROP FUNCTION IF EXISTS verify_execution_atomic_graph()")
    for table in (
        "risk_exposure_state_history",
        "order_intent_state_history",
        "risk_ledger_entries",
        "risk_reservations",
        "execution_facts",
        "order_intents",
        "execution_risk_decisions",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_immutable ON {table}")
    op.execute("DROP FUNCTION IF EXISTS deny_execution_fact_change()")
